name: Build and Release Resource Pack

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create resource pack zip
        run: |
          ZIP_NAME="Whimscape-x-Create-1.21.1_r${{ github.run_number }}.zip"
          zip -r "$ZIP_NAME" \
            assets/ \
            pack.mcmeta \
            pack.png \
            -x "*.aseprite"
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: r${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          generate_release_notes: true
          draft: false
          prerelease: false

      - name: Upload Resource Pack to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ZIP_NAME }}
          asset_name: ${{ env.ZIP_NAME }}
          asset_content_type: application/zip

      - name: Upload to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: sR2V0LIy
          version: "1.21.1_r${{ github.run_number }}"
          channel: beta
          files: ${{ env.ZIP_NAME }}
          loaders: |-
            minecraft
          game-versions: |-
            1.21.1
